version: "3"

# Modern, optimized Taskfile with dependency tracking and best practices

includes:
  amp:
    taskfile: ./agentic-mesh-protocol/Taskfile.yml
    dir: ./agentic-mesh-protocol
    optional: true

vars:
  PACKAGE_NAME: agentic_mesh_protocol
  PACKAGE_DIR: src/{{.PACKAGE_NAME}}
  BUF_PACKAGE_DIR: src/buf
  PROTO_FOLDER: agentic-mesh-protocol
  PROTO_GEN_DIR: "{{.PROTO_FOLDER}}/gen/python"
  PYTHON: uv run

dotenv: [".env"]

tasks:
  # ==============================================================================
  # Default
  # ==============================================================================
  default:
    desc: List available tasks
    cmds:
      - task --list

  # ==============================================================================
  # Setup & Installation
  # ==============================================================================

  init:
    desc: Initialize git submodules
    aliases: [submodule]
    cmds:
      - git submodule update --init --recursive
    status:
      - test -f {{.PROTO_FOLDER}}/.git

  install:
    desc: Install Python dependencies
    aliases: [deps, sync]
    cmds:
      - uv sync
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - .venv/**/*

  install:amp:
    desc: Install agentic-mesh-protocol npm dependencies
    aliases: [amp-install]
    deps: [init]
    cmds:
      - task: amp:install
    status:
      - test -d {{.PROTO_FOLDER}}/node_modules

  setup:
    desc: Complete development environment setup
    aliases: [bootstrap]
    cmds:
      - task: init
      - task: amp:install
      - task: install
      - task: install:hooks

  install:hooks:
    desc: Install pre-commit hooks
    cmds:
      - "{{.PYTHON}} pre-commit install --install-hooks"
    status:
      - test -f .git/hooks/pre-commit
    preconditions:
      - sh: command -v pre-commit >/dev/null 2>&1 || {{.PYTHON}} pre-commit --version
        msg: "pre-commit not available"

  dev:
    desc: Quick development setup
    cmds:
      - task: setup
      - task: gen
      - echo "Development environment ready!"

  # ==============================================================================
  # Proto Generation
  # ==============================================================================

  proto:init:
    desc: Ensure proto submodule is initialized
    internal: true
    cmds:
      - task: init
    status:
      - test -f {{.PROTO_FOLDER}}/.git

  proto:generate:
    desc: Generate Python code from proto files using buf
    internal: true
    deps: ["proto:init", "install:amp"]
    cmds:
      - task: amp:generate
    sources:
      - "{{.PROTO_FOLDER}}/proto/**/*.proto"
      - "{{.PROTO_FOLDER}}/buf.gen.yaml"
    generates:
      - "{{.PROTO_GEN_DIR}}/**/*.py"
      - "{{.PROTO_GEN_DIR}}/**/*.pyi"

  proto:copy:
    desc: Copy generated proto files to package
    internal: true
    deps: ["proto:generate"]
    cmds:
      - mkdir -p {{.PACKAGE_DIR}}
      - mkdir -p {{.BUF_PACKAGE_DIR}}
      # Copy agentic_mesh_protocol (content only, preserving __version__.py, __init__.py, py.typed)
      - rsync -av --delete --exclude='__pycache__' --exclude='__version__.py' --exclude='__init__.py' --exclude='py.typed' {{.PROTO_GEN_DIR}}/agentic_mesh_protocol/ {{.PACKAGE_DIR}}/
      # Copy buf
      - rsync -av --delete --exclude='__pycache__' --exclude='__init__.py' {{.PROTO_GEN_DIR}}/buf/ {{.BUF_PACKAGE_DIR}}/
    sources:
      - "{{.PROTO_GEN_DIR}}/**/*.py"
      - "{{.PROTO_GEN_DIR}}/**/*.pyi"
    generates:
      - "{{.PACKAGE_DIR}}/**/*.py"
      - "{{.BUF_PACKAGE_DIR}}/**/*.py"

  gen:
    desc: Complete proto generation pipeline
    aliases: [generate, gen-proto, proto]
    cmds:
      - task: proto:init
      - task: proto:generate
      - task: proto:copy
      - task: proto:ensure-init
      - task: proto:create-namespaces
      - task: build

    summary: |
      Generates Python code from Protocol Buffer definitions.

      Steps:
      1. Initialize submodule
      2. Run buf generate in agentic-mesh-protocol (via amp:generate)
         - Generates code for local proto files AND buf.build/bufbuild/protovalidate
      3. Copy generated files to src/agentic_mesh_protocol/ and src/buf/
      4. Ensure __init__.py files exist in all directories
      5. Ensure buf package has __init__.py files
      6. Build package

  proto:ensure-init:
    desc: Ensure all directories have __init__.py files
    internal: true
    cmds:
      - find "{{.PACKAGE_DIR}}" -type d ! -path "*/__pycache__*" -exec sh -c 'test -f "$1/__init__.py" || touch "$1/__init__.py"' _ {} \;
      - find "{{.BUF_PACKAGE_DIR}}" -type d ! -path "*/__pycache__*" -exec sh -c 'test -f "$1/__init__.py" || touch "$1/__init__.py"' _ {} \;

  proto:create-namespaces:
    desc: Ensure buf package has __init__.py files for import compatibility
    internal: true
    cmds:
      - touch {{.BUF_PACKAGE_DIR}}/__init__.py 2>/dev/null || true
      - touch {{.BUF_PACKAGE_DIR}}/validate/__init__.py 2>/dev/null || true

  proto:clean:
    desc: Clean generated proto files (preserves __version__.py, __init__.py, py.typed)
    cmds:
      - rm -rf {{.PACKAGE_DIR}}/module {{.PACKAGE_DIR}}/cost {{.PACKAGE_DIR}}/filesystem
      - rm -rf {{.PACKAGE_DIR}}/module_registry {{.PACKAGE_DIR}}/setup {{.PACKAGE_DIR}}/storage
      - rm -rf {{.PACKAGE_DIR}}/user_profile
      - rm -rf {{.BUF_PACKAGE_DIR}}/validate
      - rm -rf {{.PROTO_FOLDER}}/gen

  proto:lint:
    desc: Lint proto files with buf
    cmds:
      - task: amp:lint

  proto:format:
    desc: Format proto files with buf
    cmds:
      - task: amp:format

  proto:format:check:
    desc: Check proto file formatting
    cmds:
      - task: amp:format:check

  proto:breaking:
    desc: Check for breaking changes in proto files
    cmds:
      - task: amp:breaking

  # ==============================================================================
  # Code Quality
  # ==============================================================================

  fmt:
    desc: Format code with ruff
    aliases: [format]
    cmds:
      - "{{.PYTHON}} ruff format ."
    sources:
      - "**/*.py"
      - .ruff.toml
      - pyproject.toml

  lint:fix:
    desc: Lint and auto-fix issues
    aliases: [fix]
    cmds:
      - task: fmt
      - "{{.PYTHON}} ruff check --fix ."

  lint:
    desc: Check code quality (format + lint + type check)
    cmds:
      - task: lint:format
      - task: lint:ruff

  lint:format:
    desc: Check code formatting
    internal: true
    cmds:
      - "{{.PYTHON}} ruff format --check --diff ."

  lint:ruff:
    desc: Lint code with ruff
    internal: true
    cmds:
      - "{{.PYTHON}} ruff check ."

  pre-commit:
    desc: Run all pre-commit hooks
    cmds:
      - "{{.PYTHON}} pre-commit run --all-files"

  # ==============================================================================
  # Testing
  # ==============================================================================

  test:
    desc: Run test suite
    aliases: [t]
    cmds:
      - "{{.PYTHON}} pytest {{.CLI_ARGS}}"
    sources:
      - "{{.PACKAGE_DIR}}/**/*.py"
      - test/**/*.py
      - tests/**/*.py
      - pyproject.toml

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - "{{.PYTHON}} pytest-watch {{.CLI_ARGS}}"

  # ==============================================================================
  # Building & Publishing
  # ==============================================================================

  build:
    desc: Build Python package
    aliases: [build-package]
    deps: ["proto:ensure-init"]
    cmds:
      - uv build
    sources:
      - "{{.PACKAGE_DIR}}/**/*.py"
      - "{{.PACKAGE_DIR}}/**/*.pyi"
      - pyproject.toml
      - README.md
    generates:
      - dist/*.whl
      - dist/*.tar.gz

  publish:test:
    desc: Publish package to TestPyPI
    aliases: [publish-test]
    deps: [build]
    cmds:
      - uv publish --repository-url https://test.pypi.org/legacy/ {{.CLI_ARGS}}
    preconditions:
      - sh: test -n "$(ls -A dist 2>/dev/null)"
        msg: "No built packages found in dist/. Run 'task build' first."

  publish:prod:
    desc: Publish package to PyPI
    aliases: [publish, release]
    deps: [build]
    cmds:
      - uv publish {{.CLI_ARGS}}
    preconditions:
      - sh: test -n "$(ls -A dist 2>/dev/null)"
        msg: "No built packages found in dist/. Run 'task build' first."
      - sh: '[ "$(git rev-parse --abbrev-ref HEAD)" = "main" ] || echo "WARNING: Not on main branch"'

  # ==============================================================================
  # Version Management
  # ==============================================================================

  bump-version:
    desc: "Bump package version (type: major, minor, patch, release_type or release_num)"
    cmds:
      - SKIP=pytest bump-my-version bump {{.CLI_ARGS}}

  version:update-submodule:
    desc: Update proto submodule to latest dev
    internal: true
    cmds:
      - git submodule update --remote --merge {{.PROTO_FOLDER}}

  # ==============================================================================
  # CI/CD
  # ==============================================================================

  ci:
    desc: Run full CI pipeline
    cmds:
      - task: lint
      - task: test
      - task: build

  ci:quick:
    desc: Quick CI checks (lint only)
    cmds:
      - task: lint:format
      - task: lint:ruff

  check:
    desc: Quick health check
    cmds:
      - task: validate
      - task: ci:quick
      - echo "All checks passed!"

  validate:
    desc: Validate development environment
    cmds:
      - command -v uv >/dev/null 2>&1 || { echo "uv not found"; exit 1; }
      - command -v task >/dev/null 2>&1 || { echo "task not found"; exit 1; }
      - command -v rsync >/dev/null 2>&1 || { echo "rsync not found"; exit 1; }
      - echo "All required tools are installed"

  # ==============================================================================
  # Cleanup
  # ==============================================================================

  clean:
    desc: Remove build artifacts and cache directories
    cmds:
      - rm -rf dist src/{{.PACKAGE_NAME}}.egg-info
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true

  clean:full:
    desc: Deep clean (generated code + venv + all artifacts)
    aliases: [clean-all, reset]
    cmds:
      - task: clean
      - task: proto:clean
      - rm -rf .venv
