version: "3"

vars:
  # could use env var
  PACKAGE_NAME: "service_apis_py"
  PACKAGE_DIR: "src/{{.PACKAGE_NAME}}"
  PROTO_FOLDER: "service-apis"
  PROTO_PATH: "{{.PROTO_FOLDER}}/proto"

tasks:
  install-proto-repo:
    desc: "Install project proto submodule from repo service-apis"
    cmds:
      - git submodule update --init --recursive

  build-proto:
    desc: "Build project proto from submodule"
    cmds:
      - buf dep update {{.PROTO_PATH}}
      - |
        buf generate {{.PROTO_PATH}} --template {{.PROTO_PATH}}/buf.gen.py.yaml \
        --include-imports \
        -o src/{{.PACKAGE_NAME}} \
        --path {{.PROTO_PATH}}/digitalkin/module \
        --path {{.PROTO_PATH}}/digitalkin/module_registry

  process-proto:
    desc: "Clean project proto import in generated files from submodule"
    cmds:
      - |
        find {{.PACKAGE_DIR}} -type f -name '*.py' -exec sed -i -r 's/^(from|import)[[:space:]]+((google\.api|digitalkin\.|buf\.validate)[^[:space:]]*)/\1 {{.PACKAGE_NAME}}.\2/' {} +

  venv:
    desc: "Install project venv"
    cmds:
      - uv venv --python 3.10

  install-deps:
    desc: "Install project dependencies from pyproject.toml"
    cmds:
      - uv pip compile pyproject.toml

  build-package:
    desc: "Build the PyPI package (runs your build script)"
    cmds:
      - |
        # Find all directories within the target directory and add __init__.py if not present
        find "{{.PACKAGE_DIR}}" -type d -exec bash -c 'touch "$0/__init__.py"' {} \;
      - uv build

  publish-package-test:
    desc: "Publish the package to the PyPI's test env"
    cmds:
      - uv publish

  test-package:
    desc: "Test if the the PyPI package is well published"
    cmds:
      - uv run --with {{.PACKAGE_NAME}} --no-project -- python -c \"import {{.PACKAGE_NAME}}\"

  clean:
    desc: "Test if the the PyPI package is well published"
    cmds:
      - rm -rf dist src

  gen-proto:
    desc: "Install, update and build protobuff file for python"
    cmds:
      - task: install-proto-repo
      - task: build-proto
      - task: process-proto

  gen-package:
    desc: "Install, update and build protobuff file for python"
    cmds:
      - task: install-deps
      - task: build-package

  test-publish:
    desc: "push and test the package in a test env"
    cmds:
      - task: publish-package-test
      - task: test-package

  all:
    desc: "Run all steps: init, install, and build"
    cmds:
      - task: gen-proto
      - task: gen-package
      # - test-publish
