name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    # Only run if PR is merged and contains version bump
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/bump-')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version
      id: get_version
      run: |
        VERSION=$(grep -m 1 "version = " pyproject.toml | cut -d '"' -f 2)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create tag
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git tag -a v${{ steps.get_version.outputs.version }} -m "Release v${{ steps.get_version.outputs.version }}"
        git push origin v${{ steps.get_version.outputs.version }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        generateReleaseNotes: true
