name: Create Version Bump PR

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  create-version-bump-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install bump2version

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Create release branch
      run: |
        BRANCH_NAME="release/bump-${{ github.event.inputs.version_type }}-version-$(date +'%Y%m%d%H%M%S')"
        git checkout -b $BRANCH_NAME
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Bump version
      run: |
        # Use --no-tag to prevent bump2version from creating a tag
        # The tag will be created after the PR is merged
        bump2version --no-tag ${{ github.event.inputs.version_type }}

    - name: Get new version
      id: get_version
      run: |
        VERSION=$(grep -m 1 "version = " pyproject.toml | cut -d '"' -f 2)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Push changes to new branch
      run: git push --set-upstream origin $BRANCH_NAME

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ env.BRANCH_NAME }}
        destination_branch: "main"
        pr_title: "Bump version to ${{ steps.get_version.outputs.version }}"
        pr_body: |
          Automated version bump by GitHub Actions
          - Version type: ${{ github.event.inputs.version_type }}
          - New version: ${{ steps.get_version.outputs.version }}

          Once merged, a new release will be created automatically.
        pr_label: "automated,version-bump"
        github_token: ${{ secrets.GITHUB_TOKEN }}
